import type {
  Accident,
  Claim,
  DocumentItem,
  DriverProfile,
  Expense,
  FuelLog,
  MaintenanceEvent,
  PassportEvent,
  Provider,
  ReminderItem,
  SymptomRecord,
  TrackerInfo,
  Vehicle,
} from "./types";

export const vehicle: Vehicle = {
  id: "v1",
  brand: "Toyota",
  model: "Corolla Cross",
  trim: "HEV Premium Luxury",
  year: 2022,
  plate: "1กข 1234",
  province: "กรุงเทพมหานคร",
  color: "ขาวมุก (White Pearl)",
  vin: "MR053CHK5N1234567",
  mileage: 88450,
  purchaseDate: "2022-03-15",
  purchasePrice: 1179000,
  image: "/vehicle-corolla-cross.svg",
};

export const initialTrackers: TrackerInfo[] = [
  {
    key: "oil",
    label: "น้ำมันเครื่อง",
    labelEn: "Engine Oil",
    lastDate: "2026-05-18",
    lastMileage: 80000,
    intervalKm: 10000,
    intervalMonths: 6,
    nextDueMileage: 90000,
    nextDueDate: "2026-11-18",
    status: "dueSoon",
    icon: "🛢️",
  },
  {
    key: "battery",
    label: "แบตเตอรี่",
    labelEn: "Battery",
    lastDate: "2022-03-15",
    lastMileage: 0,
    intervalKm: 60000,
    intervalMonths: 36,
    nextDueMileage: 60000,
    nextDueDate: "2025-03-15",
    status: "urgent",
    icon: "🔋",
  },
  {
    key: "tire",
    label: "ยาง",
    labelEn: "Tires",
    lastDate: "2026-06-02",
    lastMileage: 82000,
    intervalKm: 10000,
    intervalMonths: 6,
    nextDueMileage: 92000,
    nextDueDate: "2026-12-02",
    status: "warning",
    icon: "🛞",
  },
  {
    key: "brake",
    label: "เบรก",
    labelEn: "Brake",
    lastDate: "2026-08-05",
    lastMileage: 87200,
    intervalKm: 20000,
    intervalMonths: 12,
    nextDueMileage: 107200,
    nextDueDate: "2027-08-05",
    status: "healthy",
    icon: "🛑",
  },
  {
    key: "aircon",
    label: "แอร์",
    labelEn: "Air Conditioning",
    lastDate: "2026-02-10",
    lastMileage: 81500,
    intervalKm: 15000,
    intervalMonths: 12,
    nextDueMileage: 96500,
    nextDueDate: "2027-02-10",
    status: "healthy",
    icon: "❄️",
  },
  {
    key: "injector",
    label: "หัวฉีด",
    labelEn: "Injector",
    lastDate: "2025-11-20",
    lastMileage: 75300,
    intervalKm: 20000,
    intervalMonths: 24,
    nextDueMileage: 95300,
    nextDueDate: "2027-11-20",
    status: "healthy",
    icon: "💉",
  },
];

export const initialMaintenanceEvents: MaintenanceEvent[] = [
  {
    id: "m1",
    category: "general",
    title: "เช็คระยะ 78,000 km ตามศูนย์",
    date: "2026-01-10",
    mileage: 78900,
    cost: 3200,
    location: "Toyota Sure ลาดพร้าว",
  },
  {
    id: "m2",
    category: "aircon",
    title: "ล้างแอร์ + เติมน้ำยาแอร์",
    date: "2026-02-10",
    mileage: 81500,
    cost: 1200,
    location: "AutoCare Express พระราม 9",
  },
  {
    id: "m3",
    category: "oil",
    title: "เปลี่ยนน้ำมันเครื่อง + ไส้กรองน้ำมันเครื่อง",
    date: "2026-05-18",
    mileage: 80000,
    cost: 2450,
    location: "Toyota Sure ลาดพร้าว",
  },
  {
    id: "m4",
    category: "tire",
    title: "สลับยาง 4 ล้อ",
    date: "2026-06-02",
    mileage: 82000,
    cost: 400,
    location: "AutoCare Express พระราม 9",
  },
  {
    id: "m5",
    category: "brake",
    title: "ตรวจเบรกตามระยะ - ผลปกติ",
    date: "2026-08-05",
    mileage: 87200,
    cost: 0,
    location: "Toyota Sure ลาดพร้าว",
  },
  {
    id: "m6",
    category: "injector",
    title: "ล้างหัวฉีด",
    date: "2025-11-20",
    mileage: 75300,
    cost: 1500,
    location: "Bosch Car Service สุขุมวิท",
  },
  {
    id: "m7",
    category: "general",
    title: "ซ่อมกันชนหลังหลังเกิดอุบัติเหตุ",
    date: "2024-03-05",
    mileage: 42300,
    cost: 12000,
    location: "อู่ในเครือประกันวิริยะ",
    notes: "เคลมประกัน - ดูรายละเอียดในอุบัติเหตุ/เคลม",
  },
];

export const initialExpenses: Expense[] = [
  { id: "e1", category: "fuel", title: "เติมน้ำมัน Gasohol 95", date: "2026-08-05", amount: 1116 },
  { id: "e2", category: "fuel", title: "เติมน้ำมัน Gasohol 95", date: "2026-08-20", amount: 1090 },
  { id: "e3", category: "toll", title: "ทางด่วน", date: "2026-08-22", amount: 130 },
  { id: "e4", category: "carwash", title: "ล้างรถ", date: "2026-08-24", amount: 250 },
  { id: "e5", category: "maintenance", title: "ตรวจเบรกตามระยะ", date: "2026-08-05", amount: 0 },
  { id: "e6", category: "parking", title: "ที่จอดรถห้าง", date: "2026-09-01", amount: 80 },
  { id: "e7", category: "fuel", title: "เติมน้ำมัน Gasohol 95", date: "2026-09-05", amount: 1185 },
  { id: "e8", category: "toll", title: "ทางด่วน", date: "2026-09-06", amount: 110 },
  { id: "e9", category: "parking", title: "ที่จอดรถออฟฟิศ", date: "2026-09-08", amount: 200 },
  { id: "e10", category: "carwash", title: "ล้างรถ + ดูดฝุ่น", date: "2026-09-09", amount: 280 },
  { id: "e11", category: "insurance", title: "เบี้ยประกันชั้น 1 (รายปี)", date: "2025-10-23", amount: 18500 },
  { id: "e12", category: "tax", title: "ต่อภาษีรถยนต์", date: "2025-11-30", amount: 2400 },
  { id: "e13", category: "maintenance", title: "เปลี่ยนน้ำมันเครื่อง", date: "2026-05-18", amount: 2450 },
  { id: "e14", category: "maintenance", title: "ล้างแอร์ + เติมน้ำยา", date: "2026-02-10", amount: 1200 },
];

export const initialFuelLogs: FuelLog[] = [
  { id: "f1", date: "2026-08-05", liters: 31.0, pricePerLiter: 36.0, totalCost: 1116, mileage: 87000, fuelType: "Gasohol 95" },
  { id: "f2", date: "2026-08-20", liters: 30.1, pricePerLiter: 36.2, totalCost: 1090, mileage: 87600, fuelType: "Gasohol 95" },
  { id: "f3", date: "2026-09-05", liters: 32.5, pricePerLiter: 36.45, totalCost: 1185, mileage: 88200, fuelType: "Gasohol 95" },
];

export const initialReminders: ReminderItem[] = [
  {
    id: "r1",
    title: "เปลี่ยนน้ำมันเครื่อง",
    type: "mileage",
    dueMileage: 90000,
    category: "maintenance",
    status: "dueSoon",
    icon: "🛢️",
  },
  {
    id: "r2",
    title: "ตรวจ/เปลี่ยนแบตเตอรี่",
    type: "date",
    dueDate: "2025-03-15",
    category: "maintenance",
    status: "urgent",
    icon: "🔋",
  },
  {
    id: "r3",
    title: "ต่อประกันภัยชั้น 1",
    type: "date",
    dueDate: "2026-10-23",
    category: "legal",
    status: "dueSoon",
    icon: "🛡️",
  },
  {
    id: "r4",
    title: "ต่อ พ.ร.บ.",
    type: "date",
    dueDate: "2026-10-05",
    category: "legal",
    status: "urgent",
    icon: "📄",
  },
  {
    id: "r5",
    title: "ใบขับขี่ใกล้หมดอายุ",
    type: "date",
    dueDate: "2026-10-16",
    category: "legal",
    status: "dueSoon",
    icon: "🆔",
  },
  {
    id: "r6",
    title: "ต่อภาษีรถยนต์ (ป้ายวงกลม)",
    type: "date",
    dueDate: "2026-11-30",
    category: "legal",
    status: "warning",
    icon: "🏷️",
  },
  {
    id: "r7",
    title: "สลับยาง",
    type: "mileage",
    dueMileage: 92000,
    category: "maintenance",
    status: "warning",
    icon: "🛞",
  },
];

export const initialDocuments: DocumentItem[] = [
  { id: "d1", title: "เล่มทะเบียนรถ", category: "registration", status: "active", addedDate: "2022-03-20" },
  { id: "d2", title: "กรมธรรม์ประกันภัยชั้น 1 (วิริยะประกันภัย)", category: "insurance", status: "dueSoon", expireDate: "2026-10-23", addedDate: "2025-10-23" },
  { id: "d3", title: "พ.ร.บ. คุ้มครองผู้ประสบภัย", category: "cmi", status: "dueSoon", expireDate: "2026-10-05", addedDate: "2025-10-05" },
  { id: "d4", title: "ใบเสร็จภาษีรถยนต์", category: "roadtax", status: "active", expireDate: "2026-11-30", addedDate: "2025-11-30" },
  { id: "d5", title: "ใบรับรองตรวจสภาพ (ตรอ.)", category: "inspection", status: "active", addedDate: "2022-03-20" },
  { id: "d6", title: "บัตรรับประกัน Toyota (5 ปี / 100,000 กม.)", category: "warranty", status: "dueSoon", expireDate: "2027-03-15", addedDate: "2022-03-15" },
  { id: "d7", title: "สัญญาเช่าซื้อ / ไฟแนนซ์", category: "finance", status: "active", addedDate: "2022-03-15" },
  { id: "d8", title: "ใบขับขี่", category: "license", status: "dueSoon", expireDate: "2026-10-16", addedDate: "2021-10-16" },
  { id: "d9", title: "ใบเสร็จเปลี่ยนน้ำมันเครื่อง", category: "invoice", status: "active", addedDate: "2026-05-18" },
  { id: "d10", title: "ใบรับรองซ่อม - เปลี่ยนหัวฉีด", category: "service", status: "active", addedDate: "2025-11-20" },
];

export const symptomRecords: SymptomRecord[] = [
  {
    id: "s1",
    title: "มีเสียงดังผิดปกติตอนเข้าโค้ง",
    date: "2026-08-28",
    severity: "medium",
    notes: "ได้ยินเสียง 'แกร็ก' เบาๆ เฉพาะตอนเลี้ยวซ้ายความเร็วต่ำ",
  },
];

export const accidents: Accident[] = [
  {
    id: "a1",
    date: "2024-03-02",
    location: "แยกรัชโยธิน กรุงเทพมหานคร",
    detail: "ถูกรถคันหลังชนท้ายเบาๆ ขณะจอดติดสัญญาณไฟแดง กันชนหลังบุบเล็กน้อย",
    claimId: "c1",
  },
];

export const claims: Claim[] = [
  {
    id: "c1",
    accidentId: "a1",
    insurer: "วิริยะประกันภัย",
    date: "2024-03-05",
    status: "closed",
    amount: 12000,
  },
];

export const initialPassportEvents: PassportEvent[] = [
  { id: "p1", date: "2022-03-15", type: "purchase", title: "ซื้อรถใหม่ป้ายแดง", detail: "Toyota Corolla Cross HEV Premium Luxury ราคา 1,179,000 บาท", icon: "🚗" },
  { id: "p2", date: "2022-03-20", type: "legal", title: "จดทะเบียน + เริ่มความคุ้มครองประกัน", detail: "จดทะเบียนป้าย 1กข 1234 กรุงเทพมหานคร พร้อมประกันชั้น 1 และ พ.ร.บ.", icon: "📄" },
  { id: "p3", date: "2023-10-23", type: "legal", title: "ต่อประกันภัยชั้น 1", detail: "ต่ออายุกรมธรรม์กับวิริยะประกันภัย", icon: "🛡️" },
  { id: "p4", date: "2024-03-02", type: "accident", title: "อุบัติเหตุ - ถูกชนท้าย", detail: "แยกรัชโยธิน กรุงเทพมหานคร กันชนหลังบุบเล็กน้อย", icon: "⚠️" },
  { id: "p5", date: "2024-03-05", type: "claim", title: "เคลมประกัน - ปิดเคสแล้ว", detail: "วิริยะประกันภัย จ่ายค่าซ่อม 12,000 บาท", icon: "✅" },
  { id: "p6", date: "2024-10-23", type: "legal", title: "ต่อประกันภัยชั้น 1", detail: "ต่ออายุกรมธรรม์ประจำปี", icon: "🛡️" },
  { id: "p7", date: "2025-10-23", type: "legal", title: "ต่อประกันภัยชั้น 1", detail: "ต่ออายุกรมธรรม์ประจำปี", icon: "🛡️" },
  { id: "p8", date: "2025-11-20", type: "maintenance", title: "ล้างหัวฉีด", detail: "Bosch Car Service สุขุมวิท ที่เลขไมล์ 75,300 กม.", icon: "💉" },
  { id: "p9", date: "2026-01-10", type: "maintenance", title: "เช็คระยะ 78,000 km", detail: "Toyota Sure ลาดพร้าว", icon: "🔧" },
  { id: "p10", date: "2026-02-10", type: "maintenance", title: "ล้างแอร์ + เติมน้ำยา", detail: "AutoCare Express พระราม 9 ที่เลขไมล์ 81,500 กม.", icon: "❄️" },
  { id: "p11", date: "2026-05-18", type: "maintenance", title: "เปลี่ยนน้ำมันเครื่อง", detail: "Toyota Sure ลาดพร้าว ที่เลขไมล์ 80,000 กม.", icon: "🛢️" },
  { id: "p12", date: "2026-06-02", type: "maintenance", title: "สลับยาง 4 ล้อ", detail: "AutoCare Express พระราม 9 ที่เลขไมล์ 82,000 กม.", icon: "🛞" },
  { id: "p13", date: "2026-08-05", type: "maintenance", title: "ตรวจเบรกตามระยะ", detail: "ผลตรวจปกติ ที่เลขไมล์ 87,200 กม.", icon: "🛑" },
];

export const providers: Provider[] = [
  {
    id: "pr1",
    name: "Toyota Sure ลาดพร้าว",
    type: "ศูนย์บริการ",
    distanceKm: 3.2,
    rating: 4.7,
    reviewCount: 312,
    priceLevel: "฿฿฿",
    specialty: ["Toyota", "Hybrid", "ประกัน"],
    availableToday: true,
    estimatedPrice: "1,800 - 2,500 บาท",
  },
  {
    id: "pr2",
    name: "AutoCare Express พระราม 9",
    type: "อู่ทั่วไป",
    distanceKm: 1.8,
    rating: 4.5,
    reviewCount: 198,
    priceLevel: "฿฿",
    specialty: ["เปลี่ยนถ่าย", "เบรก", "แอร์"],
    availableToday: true,
    estimatedPrice: "1,200 - 1,800 บาท",
  },
  {
    id: "pr3",
    name: "QuickFix Garage รัชดา",
    type: "อู่ทั่วไป",
    distanceKm: 4.5,
    rating: 4.2,
    reviewCount: 87,
    priceLevel: "฿",
    specialty: ["ทั่วไป", "ยาง"],
    availableToday: false,
    estimatedPrice: "900 - 1,500 บาท",
  },
  {
    id: "pr4",
    name: "Bosch Car Service สุขุมวิท",
    type: "ศูนย์บริการมาตรฐาน",
    distanceKm: 6.1,
    rating: 4.8,
    reviewCount: 450,
    priceLevel: "฿฿฿",
    specialty: ["หัวฉีด", "ไฟฟ้ารถยนต์", "Hybrid"],
    availableToday: true,
    estimatedPrice: "2,000 - 3,200 บาท",
  },
  {
    id: "pr5",
    name: "มิตรยนต์ ยางและแบตเตอรี่ ลาดปลาเค้า",
    type: "ร้านยาง/แบตเตอรี่",
    distanceKm: 2.4,
    rating: 4.4,
    reviewCount: 140,
    priceLevel: "฿฿",
    specialty: ["ยาง", "แบตเตอรี่"],
    availableToday: true,
    estimatedPrice: "2,500 - 4,000 บาท",
  },
];

export const driverProfile: DriverProfile = {
  name: "กิตติ ยานยนต์เจริญ",
  licenseNumberMasked: "12X-XXX-XX6",
  licenseType: "รถยนต์ส่วนบุคคล (Type 1)",
  expireDate: "2026-10-16",
};

export const financeRecord = {
  loanAmount: 900000,
  downPayment: 279000,
  installmentAmount: 16500,
  totalInstallments: 60,
  paidInstallments: 40,
  remainingInstallments: 20,
  outstandingBalance: 330000,
  startDate: "2022-04-15",
};

export const valueRecord = {
  purchasePrice: 1179000,
  currentEstimatedValue: 780000,
  forecast1Year: 700000,
  forecast2Year: 630000,
  forecast3Year: 560000,
};

export const fuelPriceToday = {
  date: "2026-09-11",
  gasohol95: 36.45,
  gasohol91: 36.18,
  diesel: 32.94,
  changeNote: "Gasohol 95 ปรับขึ้น 0.50 บาท/ลิตร จากสัปดาห์ก่อน",
};

export const usefulTodayCards = [
  { id: "u1", icon: "🛣️", title: "วันนี้ทางด่วนบางส่วนยกเว้นค่าผ่านทาง", detail: "ทางพิเศษบางนา-อาจณรงค์ ยกเว้นค่าผ่านทางถึง 23:59 น." },
  { id: "u2", icon: "🆔", title: "ใบขับขี่ของคุณเหลืออีก 35 วัน", detail: "ควรเตรียมต่ออายุที่กรมการขนส่งทางบก" },
  { id: "u3", icon: "⛽", title: "ราคาน้ำมันปรับขึ้นวันนี้", detail: "Gasohol 95 ปรับขึ้น 0.50 บาท/ลิตร" },
];

export const trafficFine = {
  outstandingCount: 0,
  lastCheckedDate: "2026-09-01",
};
